- name: Install necessary package
  become: true
  ansible.builtin.apt:
    update_cache: true
    pkg:
      - exa
      - zsh
      - npm
      - gcc
      - unzip
      - make
      - git
      - curl
      - fzf
      - btop
      - ripgrep
- name: Install dependency
  block:
    - name: Install pip and rsync
      become: true
      ansible.builtin.apt:
        pkg:
          - python3
          - python3-pip
          - python3-venv
    - name: Install github3
      become: true
      ansible.builtin.pip:
        name:
          - github3.py
        virtualenv_command: "python3 -m venv"
        virtualenv: "{{ ansible_python_venv }}"
- name: Change python intepreter
  ansible.builtin.set_fact:
    ansible_python_interpreter: "{{ ansible_python_venv }}/bin/python3"
- name: Get latest Neovim release version
  community.general.github_release:
    repo: "fastfetch"
    user: "fastfetch-cli"
    action: latest_release
  register: fastfetch_release
- name: Fastfetch version
  ansible.builtin.debug:
    msg: "Fastfetch latest release is {{ fastfetch_release.tag }}"
- name: Set x86_84 to amd64
  ansible.builtin.set_fact:
    ansible_architecture: amd64
  when: ansible_architecture=="x86_64"
- name: Install fastfetch-cli
  become: true
  ansible.builtin.apt:
    deb: "https://github.com/fastfetch-cli/fastfetch/releases/download/{{ fastfetch_release.tag }}/fastfetch-linux-{{ ansible_architecture }}.deb"
- name: Clone dotfiles
  ansible.builtin.git:
    clone: true
    update: true
    version: main
    dest: "./dotfiles"
    repo: "https://github.com/{{ dotfiles_repo }}"
- name: Downloads newest stow
  ansible.builtin.command:
    chdir: "~/dotfiles"
    cmd: "./down_stow.sh"
    creates: "/usr/local/bin/stow"
- name: Implement dotfiles
  ansible.builtin.command:
    chdir: "~/dotfiles"
    cmd: "./impl_all.sh"
    creates: "~/.config/nvim"
- name: Change default shell
  become: true
  ansible.builtin.user:
    user: "{{ ansible_ssh_user }}"
    shell: /bin/zsh
- name: Install Neovim mod
  ansible.builtin.command:
    argv:
      - nvim
      - --headless
      - "+Lazy! sync"
      - +qa
    creates: "~/.local/share/nvim/lazy"
